using System;
using BackEndAPI.Helpers;
using NUnit.Framework;

namespace BackEndAPI_Tests.Services
{
    [TestFixture]
    public class AutoGenerator_Tests
    {

        [OneTimeSetUp]
        public void Setup()
        {
        }

        [TestCase(0)]
        [TestCase(-1)]
        public void AutoGeneratedStaffCode_ZeroOrNegaticeNumberInserted_ThrowExceptionMessage(int i)
        {
            
            //Act
            var result = Assert.Throws<InvalidOperationException>(() => AutoGenerator.AutoGeneratedStaffCode(i));

            //Assert
           Assert.AreEqual("Invalid Id", result.Message);

        }

        [OneTimeTearDown]
        public void TearDown()
        {
        }
    }
}