using System;
using System.Text.RegularExpressions;
using BackEndAPI.Interfaces;

namespace BackEndAPI.Helpers
{
    public static class AutoGenerator
    {

        public static string AutoGeneratedStaffCode(int id)
        {

            return $"SD{id.ToString("D4")}";
        }

        public static string AutoGeneratedUsername(string firstName, string lastName, IAsyncUserRepository repository)
        {

            string name = $"{firstName.ToLower()} {lastName.ToLower()}";
            string shortName = string.Empty;

            name = Regex.Replace(name, @"\s+", " ");

            string[] nameParts = name.Trim().Split(' ');

            for (var index = 0; index < nameParts.Length; index++)
            {
                var part = nameParts[index];
                if (index == 0)
                    shortName += part;
                else
                {
                    shortName += part.Substring(0, 1);
                }
            }
            var result = repository.CountUsername(shortName);
            if (result == 0) return shortName;
            return $"{shortName}{result + 1}";

        }

        public static string AutoGeneratedPassword(string username, DateTime dob)
        {
            return $"{username}@{dob.Date.ToString("ddmmyyyy")}";
        }

    }
}