using System;
using System.Text.RegularExpressions;

namespace BackEndAPI.Services
{
    public static class AutoGenerator
    {

        internal static string AutoGeneratedStaffCode(int id)
        {

            return $"SD{id.ToString("D4")}";
        }

        internal static string AutoGeneratedUsername(string firstName, string lastName)
        {

            string name = $"{firstName.ToLower()} {lastName.ToLower()}";
            string shortName = string.Empty;

            name = Regex.Replace(name, @"\s+", " ");

            string[] nameParts = name.Trim().Split(' ');

            for (var index = 0; index < nameParts.Length; index++)
            {
                var part = nameParts[index];
                if (index == 0)
                    shortName += part;
                else
                {
                    shortName += part.Substring(0, 1);
                }
            }
            
            return shortName;

        }

        internal static string AutoGeneratedPassword(string username, DateTime dob)
        {
            return $"{username}@{dob.Date.ToString("ddmmyyyy")}";
        }

    }
}